force-app/main/default/objects/Account/fields/category1__c.field-meta.xml
<CustomField>
    <fullName>category1__c</fullName>
    <label>Category *</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source1__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source*</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lead_Source__c.Lead_Mode__c</field>
            <operation>equals</operation>
            <valueField>$Source.Lead_Mode__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Source__c</referenceTo>
    <relationshipLabel>Student Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Test_preparation_required_for__c.field-meta.xml
<CustomField>
    <fullName>Test_preparation_required_for__c</fullName>
    <label>Test preparation required for</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Work_experience_in_months__c.field-meta.xml
<CustomField>
    <fullName>Total_Work_experience_in_months__c</fullName>
    <label>Total Work experience in months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/API_log__c/API_log__c.object-meta.xml
<CustomObject>
    <label>API log</label>
    <nameField>
        <label>API log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_log__c/fields/created_date__c.field-meta.xml
<CustomField>
    <fullName>created_date__c</fullName>
    <label>Request Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Log_Name__c.field-meta.xml
<CustomField>
    <fullName>Log_Name__c</fullName>
    <label>Log Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/response_time__c.field-meta.xml
<CustomField>
    <fullName>response_time__c</fullName>
    <label>Response time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/Educational_Detail__c.object-meta.xml
<CustomObject>
    <label>Educational Detail</label>
    <nameField>
        <displayFormat>EDN-{0}</displayFormat>
        <label>Educational Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Educational Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Educational_Detail__c/fields/CGPA__c.field-meta.xml
<CustomField>
    <fullName>CGPA__c</fullName>
    <label>CGPA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/EducationType__c.field-meta.xml
<CustomField>
    <fullName>EducationType__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SSC (Xth)</fullName>
            </value>
            <value>
                <fullName>HSC (XIIth)</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Post-graduation</fullName>
            </value>
            <value>
                <fullName>Professional Certification</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/Expected_Actual_Yr_of_completion__c.field-meta.xml
<CustomField>
    <fullName>Expected_Actual_Yr_of_completion__c</fullName>
    <label>Expected/Actual Yr of completion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/Marks__c.field-meta.xml
<CustomField>
    <fullName>Marks__c</fullName>
    <label>Marks</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/Qualification_Stream__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Stream__c</fullName>
    <label>Qualification/Stream</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>EducationType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Arts</fullName>
            </value>
            <value>
                <fullName>Science</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Agriculture/Fisheries/Dairy Technology</fullName>
            </value>
            <value>
                <fullName>Allied Medical Courses</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Arts/Applied Arts/Fine Arts</fullName>
            </value>
            <value>
                <fullName>Ayurvedic/Homeopathic/Unani</fullName>
            </value>
            <value>
                <fullName>Computers/IT</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Hotel/Hospitality/Travel/Tourism</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Mass Communication/Journalism</fullName>
            </value>
            <value>
                <fullName>Medical/Dental/Other Medical Courses</fullName>
            </value>
            <value>
                <fullName>Pharmacy</fullName>
            </value>
            <value>
                <fullName>Science/Home Science</fullName>
            </value>
            <value>
                <fullName>Chartered Accountancy (CA)</fullName>
            </value>
            <value>
                <fullName>Cost and Works Accountancy (ICWA)</fullName>
            </value>
            <value>
                <fullName>Company Secretaryship (CS)</fullName>
            </value>
            <value>
                <fullName>Engineering/Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/School_College__c.field-meta.xml
<CustomField>
    <fullName>School_College__c</fullName>
    <label>School/College</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/Specialisation__c.field-meta.xml
<CustomField>
    <fullName>Specialisation__c</fullName>
    <label>Specialisation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Educational_Detail__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Educational Details</relationshipLabel>
    <relationshipName>Educational_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Parent_Information__c/Parent_Information__c.object-meta.xml
<CustomObject>
    <label>Parent Information</label>
    <nameField>
        <displayFormat>PIN-{0000}</displayFormat>
        <label>Parent Information Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parent Informations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent_Information__c/fields/Parent_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Parent_Mobile__c</fullName>
    <label>Parent Mobile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Parent_Information__c/fields/Parent_Title__c.field-meta.xml
<CustomField>
    <fullName>Parent_Title__c</fullName>
    <label>Parent Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parent_Information__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Parent_Information__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Parent Informations</relationshipLabel>
    <relationshipName>Parent_Informations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/University_Board__c/University_Board__c.object-meta.xml
<CustomObject>
    <label>University/Board</label>
    <nameField>
        <label>University/Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>University/Board</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Detail__c/Work_Detail__c.object-meta.xml
<CustomObject>
    <label>Work Detail</label>
    <nameField>
        <label>Work Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Detail__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Detail__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Detail__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Details</relationshipLabel>
    <relationshipName>Work_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Detail__c/fields/Work_experience_in_months__c.field-meta.xml
<CustomField>
    <fullName>Work_experience_in_months__c</fullName>
    <label>Work experience in months</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Rest_UpdateStudentInfo.cls
@RestResource(urlMapping='/UpdateStudentInfo/*')
global class Rest_UpdateStudentInfo {
    @HttpPost
    global static void doPost() {  
        API_log__c  api_log=new API_log__c();
        api_log.Log_Name__c='UpdateStudentInfo';
       
        RestRequest request = RestContext.request;  
        
        RestResponse response = RestContext.response;  
        
        String jSONRequestBody=request.requestBody.toString().replace('\n', '');
        
        //save request in API Log
        api_log.Request__c= jSONRequestBody;
        api_log.created_date__c=Datetime.now();
        
        JSON2ApexUpdateStudentInfo jsonObj = JSON2ApexUpdateStudentInfo.parse(jSONRequestBody); 
        System.debug('======----->jsonObj'+jsonObj); 
		List<Parent_Information__c> picList=new List<Parent_Information__c>();
        List<Educational_Detail__c> edList=new List<Educational_Detail__c>();
        List<Work_Detail__c> wdList=new List<Work_Detail__c>();
        List<Account> accList=new List<Account>();
        try{
            if(jsonObj.SF_Id!=''){
                List<Account> ac=[SELECT Id,Name FROM Account WHERE Id=:jsonObj.SF_Id ];
                if(ac.size()>0){
                    Account cc=new Account();
                    cc.Id=jsonObj.SF_Id;
                    //cc.Lead_Source1__c=ldSourceId;
                    cc.FirstName = jsonObj.FirstName;
                    cc.PersonMobilePhone =jsonObj.WhatsappNumber;
                    cc.Gender__c=jsonObj.Gender;
                    cc.DOb__c=Date.valueOf(jsonObj.DOB);
                    cc.category1__c=jsonObj.Category;
                    cc.Test_preparation_required_for__c=jsonObj.TestPreparationRequiredFor;
                    cc.Total_Work_experience_in_months__c=jsonObj.TotalWork_experience_in_months;
                    for(FamilyDetails fmd:jsonObj.FamilyDetails){
                        Parent_Information__c pic=new Parent_Information__c();
                        pic.Student_Account__c=jsonObj.SF_Id;
                        pic.Relationship__c=fmd.Parent_Guardian_Relation;
                        pic.Parent_Email__c=fmd.Parent_Guardian_Email_ID;
                        pic.Parent_Mobile__c=fmd.Parent_Guardian_Mobile_No;
                        pic.Last_Name__c=fmd.Parent_Guardian_LastName;
                        pic.Middle_Name__c=fmd.Parent_Guardian_MiddleName;
                        pic.First_Name__c=fmd.Parent_Guardian_FirstName;
                       // pic.Parent_Title__c=fmd.Parent_Guardian_Title;
                        picList.add(pic);
                    }
                    
                    for(EducationalDetails ed:jsonObj.EducationalDetails){
                        Educational_Detail__c edc=new Educational_Detail__c();
                        edc.Student_Account__c=jsonObj.SF_Id;
                        edc.CGPA__c=ed.CGPA_x_y;
                        edc.EducationType__c=ed.EducationType;
                        edc.Expected_Actual_Yr_of_completion__c=ed.Expected_Actual_Yr_of_completion;
                        edc.School_College__c=ed.School_College;
                        edc.University_Board__c=ed.University_Board;
                        edc.Marks__c=ed.Marks;
                        edc.Qualification_Stream__c=ed.Qualification_Stream;
                        edc.Specialisation__c=ed.Specialisation;
                        edList.add(edc);
                    }
                    for(WorkDetails wds:jsonObj.WorkDetails){
                        Work_Detail__c wd=new Work_Detail__c();
                        wd.Student_Account__c =jsonObj.SF_Id;
                        wd.Organisation__c=wds.Organisation;
                        wd.Designation__c=wds.Designation;
                        wd.Work_experience_in_months__c=wds.Work_experience_in_months;
                        wdList.add(wd);
                    }
                    accList.add(cc);
                    
                    system.debug('wdList'+wdList);
                    upsert accList;
                    upsert wdList;
                    upsert edList;
                    upsert picList;
                    
                    String resp = JSON.serialize('{"Message":"Record updated successfully"}');
                    response.responseBody = Blob.valueOf(resp);
                    response.addHeader('Content-Type', 'application/json');
                    response.statusCode = 200;
                    api_log.Response__c= String.valueOf(resp);
                    api_log.response_time__c=Datetime.now();
                    
                }else{
                    String resp = JSON.serialize('{"Message":"Student ID is not Present"}');
                    response.responseBody = Blob.valueOf(resp);
                    response.addHeader('Content-Type', 'application/json');
                    response.statusCode = 200;
                    api_log.Response__c= String.valueOf(resp);
                    api_log.response_time__c=Datetime.now();
                }
               
            }
            
        }catch(Exception e){
            System.debug('Format Error');
            String resp = JSON.serialize('{"Message":"'+e.getStackTraceString()+'"}');
            response.responseBody = Blob.valueOf(resp);
            response.addHeader('Content-Type', 'application/json');
            
            response.statusCode = 200;
            api_log.Response__c= String.valueOf(e);
            api_log.response_time__c=Datetime.now();

        }
        insert api_log;
        
    }

    public class JSON2ApexUpdateStudentInfo {

        public String SF_Id;
        public String FirstName;
        public String LeadSource;
        public String Gender;
        public String DOB;
        public String Category;
        public String WhatsappNumber;
        public String TestPreparationRequiredFor;
        public List<FamilyDetails> FamilyDetails;
        public List<EducationalDetails> EducationalDetails;
        public List<WorkDetails> WorkDetails;
        public Integer TotalWork_experience_in_months;
    }
    
        public class EducationalDetails {
            public String EducationType;
            public String Expected_Actual_Yr_of_completion;
            public String School_College;
            public String University_Board;
            public Double Marks;
            public String CGPA_x_y;
            public String Qualification_Stream;
            public String Specialisation;
        }
    
        public class WorkDetails {
            public String Organisation;
            public String Designation;
            public Integer Work_experience_in_months;
        }
    
        public class FamilyDetails {
            public String Parent_Guardian_Title;
            public String Parent_Guardian_FirstName;
            public String Parent_Guardian_MiddleName;
            public String Parent_Guardian_LastName;
            public String Parent_Guardian_Relation;
            public String Parent_Guardian_Mobile_No;
            public String Parent_Guardian_Email_ID;
        }
    
        
        public static JSON2ApexUpdateStudentInfo parse(String json) {
            return (JSON2ApexUpdateStudentInfo) System.JSON.deserialize(json, JSON2ApexUpdateStudentInfo.class);
        }
    

}