force-app/main/default/objects/Account/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMS_PIN__c.field-meta.xml
<CustomField>
    <fullName>IMS_PIN__c</fullName>
    <label>IMS PIN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/Counselling_Centre__c.object-meta.xml
<CustomObject>
    <label>Centre*</label>
    <nameField>
        <displayFormat>CN{0000}</displayFormat>
        <label>Centre	No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centre*</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipName>Centre</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/Program_Admitted__c.object-meta.xml
<CustomObject>
    <label>Program Admitted</label>
    <nameField>
        <displayFormat>PWCN-{0000}</displayFormat>
        <label>Program Wise Centre  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Admitted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Admitted__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Program Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Program_Admitted__c.field-meta.xml
<CustomField>
    <fullName>Program_Admitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Program Admitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Interested / Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Program Admitted</relationshipLabel>
    <relationshipName>Program_Admitted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Variant_Code__c.field-meta.xml
<CustomField>
    <fullName>Variant_Code__c</fullName>
    <label>Variant Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sendStudentForEnrollment.cls
public class sendStudentForEnrollment {
    
    public Id currentId {get;set;}
    
    public sendStudentForEnrollment(){
        currentId = ApexPages.currentPage().getparameters().get('id');
        System.debug('currentId'+currentId);
    }
    
     public PageReference sendEnrollData(){
         Program_Admitted__c pg=[SELECT Id,Student_Account__r.IMS_PIN__c,Centre__r.Centre_Code__c,Variant__r.Variant_Code__c FROM Program_Admitted__c Where Id =:currentId];
         String imsPin=pg.Student_Account__r.IMS_PIN__c!=null?pg.Student_Account__r.IMS_PIN__c:'';
         String centercode=pg.Centre__r.Centre_Code__c!=null?pg.Centre__r.Centre_Code__c:'';
         String variantcode=pg.Variant__r.Variant_Code__c!=null?pg.Variant__r.Variant_Code__c:'';
         
         String limaurl='https://lima.imsindia.com/detailenrollment/default.aspx?action=addenrollment&imspin='+imsPin+'&centrecode='+centercode+'&pmvcode='+variantcode+'';
       
        System.debug('===>limaurl '+limaurl);
        PageReference pageRef = new PageReference(limaurl);
        pageRef.setRedirect(true);
        return pageRef;
       
     }

}