force-app/main/default/objects/Account/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SFDCSaveLeadRESTTest.cls
@isTest
public class SFDCSaveLeadRESTTest {
    
  
    static testmethod void test() {
        
        Id objectRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account P').getRecordTypeId();
        
        Centre__c cen = new Centre__c();
        cen.Name = 'Thane';
        cen.Centre_Code__c = '101';
        insert cen;
        
        Program__c pgrm = new Program__c();
        pgrm.Name = 'TestProgram';
        pgrm.Program_Code__c = '011';
        pgrm.Centre__c = cen.id;
        insert pgrm;
        
        Variant__c var = new Variant__c();
        var.Name = 'TestVariants';
        var.Program__c = pgrm.Id;
        var.Centre__c = cen.id;
        insert var;
        
        Account acc = new Account();
        // acc.Name = 'Test ';
        acc.LastName = 'Test';
        //acc.Variant__c=var.id;
        acc.PersonMobilePhone = '8467775437';
        acc.PersonEmail = 'raviavhad12@gmail.com';
        acc.RecordTypeId = objectRecordTypeId;
        acc.Program__c = pgrm.id;
        acc.Centre__c = cen.id;
        acc.Variant__c = var.id;
        insert acc;
        
        
        String  js = '{ \"StudentAccount\": {   \"IMSPIN\": \"IMS0000329643\",   \"Salutation\": \"\",   \"FirstName\": \"Man\",   \"MiddleName\": \"In\",   \"LastName\": \"Middle\",   \"Email\": \"ravindra@finessedirect.com\",   \"Mobile1\": \"9619462736\",   \"Mobile2\": \"9619462736\",   \"Description\": \"\",   \"MailingCity\": \"\",   \"Order\": \"\",   \"LeadStage\": \"\",   \"Preference\": \"\",   \"ReferredBy\": \"\",   \"EmployeeReferralName\": \"\",   \"StudentReferralName\": \"\",   \"ReferralCentre\": \"\",   \"LeadMode\": \"\",   \"LeadSource\": \"\",   \"Priority\": \"\",   \"ProductDeliveryMode\": \"\",   \"Productwise\": \"\",   \"MailingStreet\": \"\",   \"MailingState\": \"\",   \"MailingPinCode\": \"\",   \"MailingCountry\": \"\",   \"Street\": \"\",   \"City\": \"\",   \"State\": \"\",   \"PinCode\": \"\",   \"Country\": \"\",   \"CityCode\": \"1053\",   \"ProductCode\": \"1195\",   \"ModeCode\": \"1003\",   \"Variant\": \"2675\",   \"CentreCode\": \"446\" }}';
            
            
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        //req.requestURI = ''; //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueof(js);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
       
      
        
  //     Test.setMock(HttpCalloutMock.class, new Mock());
        SFDCSaveLeadREST.doPost();
        
        Test.stopTest();
        
    }
     static testmethod void test1() {
        
        Id objectRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account P').getRecordTypeId();
        
        Centre__c cen = new Centre__c();
        cen.Name = 'Thane';
        cen.Centre_Code__c = '101';
        insert cen;
        
        Program__c pgrm = new Program__c();
        pgrm.Name = 'TestProgram';
        pgrm.Program_Code__c = '011';
        pgrm.Centre__c = cen.id;
        insert pgrm;
        
        Variant__c var = new Variant__c();
        var.Name = 'TestVariants';
        var.Program__c = pgrm.Id;
        var.Centre__c = cen.id;
        insert var;
        
        Account acc = new Account();
        // acc.Name = 'Test ';
        acc.LastName = 'Test';
        //acc.Variant__c=var.id;
        acc.PersonMobilePhone = '8467775437';
        acc.PersonEmail = 'raviavhad12@gmail.com';
        acc.RecordTypeId = objectRecordTypeId;
        acc.Program__c = pgrm.id;
        acc.Centre__c = cen.id;
        acc.Variant__c = var.id;
        insert acc;
        
        
        String  js = '{ \"StudentAccount\": {   \"IMSPIN\": \"IMS0000329643\",   \"Salutation\": \"\",   \"FirstName\": \"Man\",   \"MiddleName\": \"In\",   \"LastName\": \"Middle\",   \"Email\": \"raviavhad12@gmail.com\",   \"Mobile1\": \"9619462736\",   \"Mobile2\": \"9619462736\",   \"Description\": \"\",   \"MailingCity\": \"\",   \"Order\": \"\",   \"LeadStage\": \"\",   \"Preference\": \"\",   \"ReferredBy\": \"\",   \"EmployeeReferralName\": \"\",   \"StudentReferralName\": \"\",   \"ReferralCentre\": \"\",   \"LeadMode\": \"\",   \"LeadSource\": \"\",   \"Priority\": \"\",   \"ProductDeliveryMode\": \"\",   \"Productwise\": \"\",   \"MailingStreet\": \"\",   \"MailingState\": \"\",   \"MailingPinCode\": \"\",   \"MailingCountry\": \"\",   \"Street\": \"\",   \"City\": \"\",   \"State\": \"\",   \"PinCode\": \"\",   \"Country\": \"\",   \"CityCode\": \"1053\",   \"ProductCode\": \"1195\",   \"ModeCode\": \"1003\",   \"Variant\": \"2675\",   \"CentreCode\": \"446\" }}';
            
            
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        
        //req.requestURI = ''; //Request URL
        req.httpMethod = 'POST'; //HTTP Request Type
        req.requestBody = Blob.valueof(js);
        RestContext.request = req;
        RestContext.response = res;
        
        Test.startTest();
       
      
        
  //     Test.setMock(HttpCalloutMock.class, new Mock());
        SFDCSaveLeadREST.doPost();
        
        Test.stopTest();
        
    }
}