force-app/main/default/objects/Account/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IMS_PIN__c.field-meta.xml
<CustomField>
    <fullName>IMS_PIN__c</fullName>
    <label>IMS PIN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/API_log__c/API_log__c.object-meta.xml
<CustomObject>
    <label>API log</label>
    <nameField>
        <label>API log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_log__c/fields/created_date__c.field-meta.xml
<CustomField>
    <fullName>created_date__c</fullName>
    <label>Request Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Exception_desc__c.field-meta.xml
<CustomField>
    <fullName>Exception_desc__c</fullName>
    <label>Exception Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Log_Name__c.field-meta.xml
<CustomField>
    <fullName>Log_Name__c</fullName>
    <label>Log Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/response_time__c.field-meta.xml
<CustomField>
    <fullName>response_time__c</fullName>
    <label>Response time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/Counselling_Centre__c.object-meta.xml
<CustomObject>
    <label>Centre*</label>
    <nameField>
        <displayFormat>CN{0000}</displayFormat>
        <label>Centre	No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centre*</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipName>Centre</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/Program_Admitted__c.object-meta.xml
<CustomObject>
    <label>Program Admitted</label>
    <nameField>
        <displayFormat>PWCN-{0000}</displayFormat>
        <label>Program Wise Centre  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Admitted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Admitted__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Program Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Program_Admitted__c.field-meta.xml
<CustomField>
    <fullName>Program_Admitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Program Admitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
                <default>true</default>
                <label>Interested</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Interested / Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Program Admitted</relationshipLabel>
    <relationshipName>Program_Admitted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Variant_Code__c.field-meta.xml
<CustomField>
    <fullName>Variant_Code__c</fullName>
    <label>Variant Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Rest_updateProgramfees.cls
@RestResource(urlMapping='/updateProgramFees/*')
global class Rest_updateProgramfees {
     @HttpPost
    global static void doPost() {  
        API_log__c  api_log=new API_log__c();
        api_log.Log_Name__c='updateProgramFees';
        
        RestRequest request = RestContext.request;  
        RestResponse response = RestContext.response;  
        
        String jSONRequestBody=request.requestBody.toString().replace('\n', '');
        api_log.Request__c= jSONRequestBody;
        api_log.created_date__c=Datetime.now();
        
       JSON2ApexSaveLead jsonObj = JSON2ApexSaveLead.parse(jSONRequestBody);
       String centre = jsonObj.StudentAccount.CentreCode;
       String product = jsonObj.StudentAccount.ProductCode;
       String varient = jsonObj.StudentAccount.Variant;
       List<Program__c> progList = [SELECT Id, Name,Program_Code__c FROM Program__c WHERE Program_Code__c=:product];
        List<Centre__c> cntreList = [SELECT Id, Name,Centre_Code__c FROM Centre__c	WHERE Centre_Code__c=:centre];
        List<Variant__c> varntList = [SELECT Id, Name, Variant_Code__c FROM Variant__c WHERE Variant_Code__c=:varient];
      
        Map<String,Id> progMap = new Map<String,Id>();
        Map<String,Id> cntreMap = new Map<String,Id>();
        Map<String,Id> varntMap = new Map<String,Id>(); 
        
        If(progList.size()>0){
            System.debug('I am printing the progList data-->'+progList);
            For(Program__c p:progList){
                progMap.put(p.Program_Code__c,p.Id);
            }
        }
        
         If(varntList.size()>0){
            System.debug('I am printing the progList data-->'+varntList);
            For(Variant__c p:varntList){
                varntMap.put(p.Variant_Code__c,p.Id);
            }
        }
        If(cntreList.size()>0){
            System.debug('I am printing the progList data-->'+cntreList);
            For(Centre__c p:cntreList){
                cntreMap.put(p.Centre_Code__c,p.Id);
            }
        }
        try{
            
       
        List<Program_Admitted__c> prgad= [SELECT Id,Amount__c,Student_Account__c,Student_Account__r.IMS_PIN__c, Name,Stage__c FROM Program_Admitted__c WHERE Program__r.Program_Code__c=:jsonObj.StudentAccount.ProductCode AND Centre__r.Centre_Code__c=:jsonObj.StudentAccount.CentreCode  AND Variant__r.Variant_Code__c=:jsonObj.StudentAccount.Variant AND Student_Account__r.IMS_PIN__c =:jsonObj.StudentAccount.IMSPIN];
       
        if(prgad.size()>0){
            for(Program_Admitted__c pg:prgad){
                     pg.Amount__c=pg.Amount__c+jsonObj.StudentAccount.Amount;
            }
            upsert prgad;
            
                Map<String, String> res_msg = new Map<String, String>();
                res_msg.put('Status', 'True');
                res_msg.put('Message', 'Amount update successfully');
                
                String resp = JSON.serialize(res_msg);
                response.responseBody = Blob.valueOf(resp);
                response.addHeader('Content-Type', 'application/json');
                response.statusCode = 200;
                
                api_log.Response__c= String.valueOf(res_msg);
                api_log.response_time__c=Datetime.now(); 
        }else{
            Map<String, String> res_msg = new Map<String, String>();
                res_msg.put('Status', 'Fail');
                res_msg.put('Message', 'no record found');
                
                String resp = JSON.serialize(res_msg);
                response.responseBody = Blob.valueOf(resp);
                response.addHeader('Content-Type', 'application/json');
                response.statusCode = 200;
                
                api_log.Response__c= String.valueOf(res_msg);
                api_log.response_time__c=Datetime.now(); 
            
        }
        
        }catch(Exception e){
            String m = e.getMessage();
            String resp = '{"Status":"False","Message":"'+e+'"}';
            response.responseBody = Blob.valueOf(resp);
            response.addHeader('Content-Type', 'application/json');
            
            response.statusCode = 400;
            api_log.Exception_desc__c=String.valueOf(resp);
        }
        insert api_log;  
    }
     public class JSON2ApexSaveLead {
        public StudentAccount StudentAccount;
    }
    public class StudentAccount {
        public String IMSPIN;
        public String ProductCode;
        public String Variant;
        public String CentreCode;
        public Decimal Amount;
    }
    
    
    
    
    public static JSON2ApexSaveLead parse(String json) {
        return (JSON2ApexSaveLead) System.JSON.deserialize(json, JSON2ApexSaveLead.class);
    }

}