force-app/main/default/objects/Account/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/Program_Admitted__c.object-meta.xml
<CustomObject>
    <label>Program Admitted</label>
    <nameField>
        <displayFormat>PWCN-{0000}</displayFormat>
        <label>Program Wise Centre  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Admitted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Admitted__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Program Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Program_Admitted__c.field-meta.xml
<CustomField>
    <fullName>Program_Admitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Program Admitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Interested / Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variant</label>
    <referenceTo>Variant__c</referenceTo>
    <relationshipLabel>Program Admitted</relationshipLabel>
    <relationshipName>Program_Admitted</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/Variant__c.object-meta.xml
<CustomObject>
    <label>Variant</label>
    <nameField>
        <label>Variant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Variants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variant__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variant__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Variants</relationshipLabel>
    <relationshipName>Variants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaveLIMALeadRESTControllerTest.cls
@isTest
public class SaveLIMALeadRESTControllerTest {
    
    
    private class Mock implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            response.setBody('{"animals": ["majestic badger", "fluffy bunny", "scary bear", "chicken", "mighty moose"]}');
            response.setStatusCode(200);
            return response; 
        }
    }
    
    
    static testmethod void test() {
        
        Id objectRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Student Account P').getRecordTypeId();
        
        List<Program__c> progList = new List<Program__c>();
        Program__c p = new Program__c();
        p.Program_Code__c = '1111';
        progList.add(p);
        
        insert progList;
        
        Centre__c c = new Centre__c();
        c.Name = 'Mumbai';
        c.Centre_Code__c = '2111';
        
        insert c;
        
        Variant__C var = new Variant__c();
        var.Program__c = progList[0].Id;
        var.Centre__c = c.Id;
        
        insert var;
        
        Account acc = new Account();
        // acc.Name = 'Test ';
        acc.LastName = 'Test';
        acc.Variant__c=var.id;
        acc.PersonMobilePhone = '8467775437';
        acc.PersonEmail = 'Test@gmail.com';
        acc.RecordTypeId = objectRecordTypeId;
        
        insert acc;
        
        Program_Admitted__c ProAddmi = new Program_Admitted__c();    
        ProAddmi.Student_Account__c = acc.id;
        ProAddmi.Program__c = p.Id;
        ProAddmi.Centre__c = c.id; 
        ProAddmi.Variant__c = var.Id;
        insert ProAddmi;
        
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new Mock()); 
        
        SaveLIMALeadRESTController s = new SaveLIMALeadRESTController();
        
        
        PageReference pageRef = Page.SaveLimaLeadAPIPage;
        test.setCurrentPageReference(pageRef);
        pageRef.getParameters().put('id',acc.id);
        s.entryAction();
        s.Cancel();
        Test.stopTest();
    }
}