force-app/main/default/objects/Account/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Child_Record__c.field-meta.xml
<CustomField>
    <fullName>Total_Child_Record__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Child Record</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Closed_Lost_No__c.field-meta.xml
<CustomField>
    <fullName>Total_Closed_Lost_No__c</fullName>
    <label>Total Closed Lost No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Enrolled_no__c.field-meta.xml
<CustomField>
    <fullName>Total_Enrolled_no__c</fullName>
    <label>Total Enrolled no</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chatbot_Lead__c/Chatbot_Lead__c.object-meta.xml
<CustomObject>
    <label>Chatbot Lead</label>
    <nameField>
        <displayFormat>CLN-{0000}</displayFormat>
        <label>Chatbot Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatbot Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chatbot_Lead__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Chatbot Leads</relationshipLabel>
    <relationshipName>Chatbot_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chatbot_Lead__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Chatbot Leads</relationshipLabel>
    <relationshipName>Chatbot_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChatbotleadConversionTest.cls
@isTest
public class ChatbotleadConversionTest {
    
    public static testMethod void ChatbotleadConversion(){
        
        Centre__c cen = new Centre__c();
        
        cen.Name = 'Dadar';
        cen.Centre_Code__c = '0129';
        cen.Email_Id__c = 'Test@gmail.com';
        insert cen;
        
        Program__c pgrm = new Program__c();
        pgrm.Name = 'CET';
        pgrm.Status__c = 'Active';
        pgrm.Centre__c = cen.id;
        insert pgrm;
        
        Account ac = new Account();
        ac.LastName='test';
        ac.Centre__c=cen.Id;
        ac.Total_Enrolled_no__c = 2;
        ac.Total_Closed_Lost_No__c =3;
        ac.Total_Child_Record__c = 1;
        
        //  ac.RecordTypeId = '0122v000000wPRuAAM';
        insert ac;
        
        Chatbot_Lead__c chat = new Chatbot_Lead__c();
        chat.Centre__c = cen.id;
        chat.Program__c = pgrm.id;
        chat.Last_Name__c = 'Benioff';
        insert chat;
        
        ApexPages.currentPage().getParameters().put('id', chat.id);
        
        ChatbotLeadConversionClass chatcll = new ChatbotLeadConversionClass();
        chatcll.Customleadconv();
         Chatbot_Lead__c ChatbotLead =  chatcll.ChatbotLead;
    }
    
}