force-app/main/default/objects/Account/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Mode</label>
    <referenceTo>Lead_Mode__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/Counselling_Centre__c.object-meta.xml
<CustomObject>
    <label>Centre*</label>
    <nameField>
        <displayFormat>CN{0000}</displayFormat>
        <label>Centre	No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centre*</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipName>Centre</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre_Code__c.field-meta.xml
<CustomField>
    <fullName>Centre_Code__c</fullName>
    <label>Centre Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Mode__c/Lead_Mode__c.object-meta.xml
<CustomObject>
    <label>Lead Mode</label>
    <nameField>
        <label>Lead Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Mode__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Lead Mode</relationshipLabel>
    <relationshipName>Lead_Mode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Mode__c/fields/Lead_Mode_Code__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode_Code__c</fullName>
    <label>Lead Mode Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Mode__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Lead Mode</relationshipLabel>
    <relationshipName>Lead_Mode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mode__c/Mode__c.object-meta.xml
<CustomObject>
    <label>Mode</label>
    <nameField>
        <label>Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mode__c/fields/Mode_Code__c.field-meta.xml
<CustomField>
    <fullName>Mode_Code__c</fullName>
    <label>Mode Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mode__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Mode</relationshipLabel>
    <relationshipName>ProgramMode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Programs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RESTGetMode.cls
global class RESTGetMode{//needs to create Schedulable  
    
    public void entryAction(){
        
        List<String> cCode = new List<String>();
        Integer totalCount =  [SELECT count() FROM Program__c];
        System.debug('Total count --->'+totalCount);
        
        For(Integer i = 0; i<=totalCount;){
            Integer max = 50;
            
            String cityCode = '';
            List<Program__c> pList = [SELECT  Id, Name,Centre__r.Name,Centre__r.Centre_Code__c,Centre__r.Id, Program_Code__c, ( SELECT  Id, Name, Mode_Code__c, Program__c FROM ProgramMode__r) FROM Program__c  ORDER BY ID LIMIT:Max Offset: i];
            List<String> centreCodeList = new List<String>();
            List<String> programCodeList = new List<String>();
            
            For(Program__c c:pList){
                
                centreCodeList.add(c.Centre__r.Centre_Code__c);
                programCodeList.add(c.Program_Code__c);
                
            }
            List<object> l= new List<object>();
            l.add(centreCodeList);
            l.add(programCodeList);
            
            
            
            
            RESTGetModeBatch rgcb = new RESTGetModeBatch(l);
            Database.executeBatch(rgcb, 50);//(rgcb,cCode);
            
            i = i+max;
            
        }
        
    }
    
    public List<String> getCode(Integer max, Integer off){
        String cityCode = '';
        List<Program__c> pList = [SELECT  Id, Name,Centre__r.Name,Centre__r.Centre_Code__c,Centre__r.Id, Program_Code__c, ( SELECT  Id, Name, Lead_Mode_Code__c,  Centre__c,  Program__c FROM Lead_Mode__r) FROM Program__c  ORDER BY ID LIMIT:Max Offset: off];
        List<String> centreCodeList = new List<String>();
        List<String> programCodeList = new List<String>();
        
        For(Program__c c:pList){
            
            centreCodeList.add(c.Centre__r.Centre_Code__c);
            programCodeList.add(c.Program_Code__c);
            
        }
        
        //System.debug('I am printing the final list of CityCode'+cityCode);
        return null;
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        String query = 'SELECT  Id, Name,Centre__r.Name,Centre__r.Centre_Code__c,Centre__r.Id, Program_Code__c, ( SELECT  Id, Name, Lead_Mode_Code__c,  Centre__c,  Program__c FROM Lead_Mode__r) FROM Program__c ';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Program__c> scope)
    {
        List<Mode> modeFromAPI = new List<Mode>();
        
        System.debug('---the centre details---');
        For(Program__c c:scope){
            //If(c.Program_Code__c=='1197'){
            List<Lead_Mode__c> ldModeDB = c.Lead_Mode__r;
            System.debug('---the program is---'+c.Lead_Mode__r);
            modeFromAPI = getCall(c.Centre__r.Centre_Code__c,c.Program_Code__c);
            For(Mode m:modeFromAPI){
                For(Lead_Mode__c ldM:ldModeDB){
                    If(m.Code==ldm.Lead_Mode_Code__c){
                        System.debug('I am printing the match Ids-->'+m);
                    }else{
                        System.debug('I am printing the unmatch Ids++>'+m);
                    }
                    
                }
            }
            
            //}
            
        }
        
        Set<String> cntre = new Set<String>();
        Set<String> prodSet = new Set<String>();
        for(Program__c c : scope)
        {
            cntre.add(c.Program_Code__c);
        }
        List<Program__c> productList = [SELECT Id, Name, Program_Code__c FROM Program__c WHERE Centre__r.Centre_Code__c IN:cntre];
        For(Program__c p:productList){
            prodSet.add(p.Program_Code__c);
        }
        
        List<Lead_Mode__c> lmode = [SELECT Id, Name From Lead_Mode__c];
        
        
    }  
    global void finish(Database.BatchableContext BC)
    {
    }
    
    
    public List<Mode> getCall(String centre,String product){
        
        String js = '{\"txtcentre\":\"'+centre+'\",\"txtproduct\":\"'+product+'\"}';
        String s = '';
        Http h = new Http();		
        HttpRequest req = new HttpRequest();
        
        req.setMethod('POST');
        req.setBody(js);
        req.setTimeout(120000);
        req.setHeader('Content-type', 'application/json');
        req.setHeader('token', s);
        req.setEndpoint('http://lima.imsindia.com/MyIMS/default.aspx?action=getmode');//sandbox url
        
        System.debug('The request is made to Datamatics-in Account---'+req);
        HttpResponse res = h.send(req);
        System.debug('The response is getting from Datamatics--in Account--'+res);
        System.debug('res.getbody'+res.getbody());
        String jsun = res.getBody();
        JSON2ApexGetMode jsCentre = JSON2ApexGetMode.parse(res.getBody());
        List<Mode> needToReturn = new List<Mode>();
        If(jsCentre.mode.size()>0){
            For(mode st:jsCentre.mode){
                System.debug('I am printing --'+st);
                needToReturn.add(st);
            }
            return needToReturn;
        }else{
            System.debug('Centre is Empty');
            return null;
        }
        
        
        
    }
    public void updateCentre(){
        
    } 
    
    //
    // Generated by JSON2Apex http://json2apex.herokuapp.com/
    //
    
    public class JSON2ApexGetMode {
        
        public List<Mode> mode;
    }
    
    public class Mode {
        public String Code;
        public String Mode;
    }
    
    
    public static JSON2ApexGetMode parse(String json) {
        return (JSON2ApexGetMode) System.JSON.deserialize(json, JSON2ApexGetMode.class);
    }
    
}