force-app/main/default/objects/Account/fields/Copy_Mailing_To_Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Copy_Mailing_To_Permanent_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Copy Mailing To Permanent Address</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Counselling</fullName>
            </value>
            <value>
                <fullName>Partially Enrolled</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Enrolled</fullName>
                <isActive>false</isActive>
                <label>Not Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/Program_Admitted__c.object-meta.xml
<CustomObject>
    <label>Program Admitted</label>
    <nameField>
        <displayFormat>PWCN-{0000}</displayFormat>
        <label>Program Wise Centre  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Admitted</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Admitted__c/fields/Program_Admitted__c.field-meta.xml
<CustomField>
    <fullName>Program_Admitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Program Admitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Program_Admitted__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Interested / Admitted</relationshipLabel>
    <relationshipName>Program_Wise_Centres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateParentInfoTest.cls
@isTest
public class CreateParentInfoTest {
    
    public static testMethod void validate(){
        
        Account acc = new Account();
        acc.LastName = 'Test';
        
        acc.ShippingPostalCode = '234532';
        acc.Lead_Stage__c = 'Open';
        acc.ShippingCity = 'THANE';
        acc.Copy_Mailing_To_Permanent_Address__c = True;
        insert acc;
        update acc;
    }
    
    public static testMethod void validate2(){
        
        Account acc = new Account();
        acc.LastName = 'Test';
        
        acc.ShippingPostalCode = '234532';
        acc.Lead_Stage__c = 'Open';
        acc.ShippingCity = 'THANE';
        acc.Copy_Mailing_To_Permanent_Address__c = True;
        insert acc;
        
        Program_Admitted__c padmit = new Program_Admitted__c();
        
        padmit.Student_Account__c = acc.Id;
        
        insert padmit;
        update padmit;
    }
    
}