force-app/main/default/objects/Account/fields/First_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>First_Lead_Source__c</fullName>
    <label>Primary Lead Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Updated_Lead_Source_Time__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated_Lead_Source_Time__c</fullName>
    <label>Last Updated Lead Source Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Mode</label>
    <referenceTo>Lead_Mode__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source1__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source*</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lead_Source__c.Lead_Mode__c</field>
            <operation>equals</operation>
            <valueField>$Source.Lead_Mode__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Source__c</referenceTo>
    <relationshipLabel>Student Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source.</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Mode_PickList__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Justdial</fullName>
            </value>
            <value>
                <fullName>Sulekha</fullName>
            </value>
            <value>
                <fullName>Urbanpro</fullName>
            </value>
            <value>
                <fullName>Shiksha</fullName>
            </value>
            <value>
                <fullName>Studysid</fullName>
            </value>
            <value>
                <fullName>Google Adwords</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>College Seminars</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Tollfree</fullName>
            </value>
            <value>
                <fullName>Email Enquiry</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Education Fairs</fullName>
            </value>
            <value>
                <fullName>IMS Events</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
                <isActive>false</isActive>
                <label>Classroom</label>
            </value>
            <value>
                <fullName>Comprehensive</fullName>
                <isActive>false</isActive>
                <label>Comprehensive</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <isActive>false</isActive>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Test Series Online</fullName>
                <isActive>false</isActive>
                <label>Test Series Online</label>
            </value>
            <value>
                <fullName>Website queries</fullName>
                <isActive>false</isActive>
                <label>Website queries</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Counselling</fullName>
            </value>
            <value>
                <fullName>Partially Enrolled</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Enrolled</fullName>
                <isActive>false</isActive>
                <label>Not Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mode_of_Coaching__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Coaching__c</fullName>
    <label>Exam Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preference__c.field-meta.xml
<CustomField>
    <fullName>Preference__c</fullName>
    <label>Preference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Category__c.field-meta.xml
<CustomField>
    <fullName>Program_Category__c</fullName>
    <label>Program Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_log__c/API_log__c.object-meta.xml
<CustomObject>
    <label>API log</label>
    <nameField>
        <label>API log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_log__c/fields/created_date__c.field-meta.xml
<CustomField>
    <fullName>created_date__c</fullName>
    <label>Request Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Log_Name__c.field-meta.xml
<CustomField>
    <fullName>Log_Name__c</fullName>
    <label>Log Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_log__c/fields/response_time__c.field-meta.xml
<CustomField>
    <fullName>response_time__c</fullName>
    <label>Response time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chatbot_Lead__c/Chatbot_Lead__c.object-meta.xml
<CustomObject>
    <label>Chatbot Lead</label>
    <nameField>
        <displayFormat>CLN-{0000}</displayFormat>
        <label>Chatbot Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatbot Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chatbot_Lead__c/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Mode</label>
    <referenceTo>Lead_Mode__c</referenceTo>
    <relationshipLabel>Chatbot Leads</relationshipLabel>
    <relationshipName>Chatbot_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chatbot_Lead__c/fields/Lead_Source1__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Lead_Source__c.Lead_Mode__c</field>
            <operation>equals</operation>
            <valueField>$Source.Lead_Mode__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Source__c</referenceTo>
    <relationshipLabel>Chatbot Leads</relationshipLabel>
    <relationshipName>Chatbot_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chatbot_Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source Pi</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Justdial</fullName>
            </value>
            <value>
                <fullName>Sulekha</fullName>
            </value>
            <value>
                <fullName>Urbanpro</fullName>
            </value>
            <value>
                <fullName>Shiksha</fullName>
            </value>
            <value>
                <fullName>Studysid</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Website queries</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>Seminars</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Tollfree</fullName>
            </value>
            <value>
                <fullName>Email Enquiry</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
            <value>
                <fullName>Test Series Online</fullName>
            </value>
            <value>
                <fullName>Correspondence</fullName>
            </value>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Google AdWords</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <label>Web to Lead Mode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Source1__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source1__c</fullName>
    <label>Web to Lead Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Mode__c/Lead_Mode__c.object-meta.xml
<CustomObject>
    <label>Lead Mode</label>
    <nameField>
        <label>Lead Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Source__c/Lead_Source__c.object-meta.xml
<CustomObject>
    <label>Lead Source</label>
    <nameField>
        <label>Lead Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Source__c/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Mode</label>
    <referenceTo>Lead_Mode__c</referenceTo>
    <relationshipLabel>Lead Sources</relationshipLabel>
    <relationshipName>Lead_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Lead_Source__c/Student_Lead_Source__c.object-meta.xml
<CustomObject>
    <label>Student Lead Source</label>
    <nameField>
        <displayFormat>LS-{0}</displayFormat>
        <label>Student Lead Source Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Lead Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Lead_Source__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Source</label>
    <referenceTo>Lead_Source__c</referenceTo>
    <relationshipLabel>Student Lead Sources</relationshipLabel>
    <relationshipName>Student_Lead_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Lead_Source__c/fields/Student_Account__c.field-meta.xml
<CustomField>
    <fullName>Student_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Student Lead Sources</relationshipLabel>
    <relationshipName>Student_Lead_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SaveChatBotLead.cls
@RestResource(urlMapping='/saveChatBotLead/*')
global class SaveChatBotLead {
    @HttpPost
    global static void doPost() {  
        
        API_log__c  api_log=new API_log__c();
        api_log.Log_Name__c='saveChatBotLead';
        RestRequest request = RestContext.request;  
        
        RestResponse response = RestContext.response;  
        
        String jSONRequestBody=request.requestBody.toString().replace('\n', '');
        api_log.Request__c= jSONRequestBody;
        api_log.created_date__c=Datetime.now();
        
        JSON2ApexSaveChatBotLead jsonObj = JSON2ApexSaveChatBotLead.parse(jSONRequestBody);  
        
        Lead_Mode__c ldMode = [SELECT Id, Name From Lead_Mode__c WHERE Name=:'Chat'];
        String ldModeId = ldMode.Id;
     
        
        Lead_Source__c ldSource = [SELECT Id, Name FROM Lead_Source__c WHERE Name =:'Chatbot'];
        String ldSourceId = ldSource.Id;
       
        
        //List<Chatbot_Lead__c> ccList = new List<Chatbot_Lead__c>();
        List<Account> ccList = new List<Account>();
        List<Account> ccList_up = new List<Account>();
        For(ChatBotLead s:jsonObj.ChatBotLead){
            List<Account> acc=[SELECT Id,MiddleName,Description,Mode_of_Coaching__c,Program_Category__c,PersonMailingCountry,PersonMailingPostalCode,PersonMailingState,PersonMailingCity,Website,PersonMailingStreet,Phone,Salutation,Suffix,PersonTitle,Preference__c,LastName,Lead_Source1__c,Name,PersonMobilePhone,Lead_Stage__c,PersonEmail FROM Account WHERE PersonMobilePhone=:s.Mobile AND FirstName=:s.FirstName AND LastName=:s.LastName LIMIT 1]; 
            System.debug('acc==>'+acc);

            if(acc.size()>0){
                if(acc[0].Lead_Stage__c =='Closed Lost' || acc[0].Lead_Stage__c =='Enrolled' || acc[0].Lead_Stage__c =='Partially Enrolled'){
                      Account cc=new Account();
               		  cc.Id=acc[0].Id;
                      cc.Lead_Stage__c='Open';
                      cc.Lead_Mode__c = ldModeId;
                      cc.Lead_Source1__c=ldSourceId;
                      cc.Last_Updated_Lead_Source_Time__c=Datetime.now();
					  cc.Salutation = (s.Salutation!='')?s.Salutation :  acc[0].Salutation; 
                      cc.LastName = (s.LastName!='')?s.LastName :  acc[0].LastName;  
                      cc.FirstName = (s.FirstName!='')?s.FirstName :  acc[0].FirstName;  
                      cc.MiddleName = (s.MiddleName!='')?s.MiddleName :  acc[0].MiddleName;  
                      cc.Suffix = (s.Suffix!='')?s.Suffix :  acc[0].Suffix;  
                      cc.PersonEmail = (s.Email!='')?s.Email :  acc[0].PersonEmail;  
                      cc.PersonMobilePhone = (s.Mobile!='')?s.Mobile :  acc[0].PersonMobilePhone;
                      cc.NumberOfEmployees = (s.NoOfEmployees!='')?Integer.valueOf(s.NoOfEmployees):  acc[0].NumberOfEmployees;
                      cc.Website = (s.Website!='')?s.Website :  acc[0].Website;
                      cc.PersonMailingCity = (s.City!='')?s.City :  acc[0].PersonMailingCity;
                      cc.PersonMailingState = (s.State!='')?s.State :  acc[0].PersonMailingState;
                      cc.PersonMailingPostalCode = (s.PostalCode!='')?s.PostalCode :  acc[0].PersonMailingPostalCode;
                      cc.Program_Category__c = (s.Program!='')?s.Program :  acc[0].Program_Category__c;
                      ccList_up.add(cc);  
                      
                }else {
                      Account cc=new Account();
               		  cc.Id=acc[0].Id;
                      cc.Lead_Mode__c = ldModeId;
                      cc.Lead_Source1__c=ldSourceId;
                      cc.Last_Updated_Lead_Source_Time__c=Datetime.now();
                      cc.Salutation = (s.Salutation!='')?s.Salutation :  acc[0].Salutation; 
                      cc.LastName = (s.LastName!='')?s.LastName :  acc[0].LastName;  
                      cc.FirstName = (s.FirstName!='')?s.FirstName :  acc[0].FirstName;  
                      cc.MiddleName = (s.MiddleName!='')?s.MiddleName :  acc[0].MiddleName;  
                      cc.Suffix = (s.Suffix!='')?s.Suffix :  acc[0].Suffix;  
                      cc.PersonEmail = (s.Email!='')?s.Email :  acc[0].PersonEmail;  
                      cc.PersonMobilePhone = (s.Mobile!='')?s.Mobile :  acc[0].PersonMobilePhone;
                      cc.NumberOfEmployees = (s.NoOfEmployees!='')?Integer.valueOf(s.NoOfEmployees):  acc[0].NumberOfEmployees;
                      cc.Website = (s.Website!='')?s.Website :  acc[0].Website;
                      cc.PersonMailingCity = (s.City!='')?s.City :  acc[0].PersonMailingCity;
                      cc.PersonMailingState = (s.State!='')?s.State :  acc[0].PersonMailingState;
                      cc.PersonMailingPostalCode = (s.PostalCode!='')?s.PostalCode :  acc[0].PersonMailingPostalCode;
                      cc.Program_Category__c = (s.Program!='')?s.Program :  acc[0].Program_Category__c;
                      ccList_up.add(cc);
                }
            }else{

            Account cc = new Account();
            cc.Salutation = s.Salutation;
            cc.Lead_Mode__c = ldModeId;
            cc.Lead_Source1__c = ldSourceId;
            cc.FirstName = s.FirstName;
            cc.MiddleName=s.MiddleName;
            if(s.LastName !=null){
                  cc.LastName = s.LastName;
            }else{
                 cc.LastName = s.FirstName;
            }
            cc.Suffix = s.Suffix;
            cc.PersonEmail = s.Email;
            cc.Website = s.Website;
            cc.PersonMobilePhone = s.Mobile;
            cc.Program_Category__c=s.Program;
            cc.NumberOfEmployees = Integer.valueOf(s.NoOfEmployees);
            cc.PersonMailingCity = s.City;
            cc.PersonMailingState = s.State;
            cc.PersonMailingPostalCode = s.PostalCode;
            cc.First_Lead_Source__c='Chatbot';
            cc.Last_Updated_Lead_Source_Time__c=Datetime.now();
            ccList.add(cc);
            } 
        }
        
        System.debug('===============---------->'+ccList);
        System.debug('===============---------->'+ccList_up);

        try{
        insert ccList;
        update ccList_up;
        //store lead source in related of account
        List<Student_Lead_Source__c> sls_list=new List<Student_Lead_Source__c>();
        for(Account acc:ccList_up){
            Student_Lead_Source__c sls=new Student_Lead_Source__c();
            sls.Lead_Source__c=ldSourceId;
            sls.Student_Account__c=acc.Id;
            sls_list.add(sls);
        }
        
        for(Account acc:ccList){
            Student_Lead_Source__c sls=new Student_Lead_Source__c();
            sls.Lead_Source__c=ldSourceId;
            sls.Student_Account__c=acc.Id;
            sls_list.add(sls);
        }
        
            upsert sls_list;
            String resp = JSON.serialize('{"Message":"Data Saved Successfully"}');
            response.responseBody = Blob.valueOf(resp);
            response.addHeader('Content-Type', 'application/json');
            response.statusCode = 200;
            api_log.Response__c= String.valueOf(resp);
            api_log.response_time__c=Datetime.now();
            
        }catch(Exception e){
            System.debug('Format Error');
            String resp = JSON.serialize('{"Message":"Data Format Error"}');
            response.responseBody = Blob.valueOf(resp);
            response.addHeader('Content-Type', 'application/json');

            response.statusCode = 200;
            api_log.Response__c= String.valueOf(resp);
            api_log.response_time__c=Datetime.now();
            
        }
        insert api_log;
    }  
    
    //
// Generated by JSON2Apex http://json2apex.herokuapp.com/
//

public class JSON2ApexSaveChatBotLead {
    public List<ChatBotLead> ChatBotLead;
}

	public class ChatBotLead {
		//public String LeadStatus;
		public String Owner;
		public String Salutation;
		public String Website;
	    public String FirstName;
	    public String MiddleName;
		public String Company;
		public String LastName;
		public String NoOfEmployees;
		public String Suffix;
       
		public String LeadSource;
		public String Title;

        public String Program;

		public String Email;
		public String Phone;
		public String Mobile;
		public String Rating;
		public String Street;
		public String City;
		public String State;
		public String PostalCode;
		public String Country;
	}

	

	
	public static JSON2ApexSaveChatBotLead parse(String json) {
		return (JSON2ApexSaveChatBotLead) System.JSON.deserialize(json, JSON2ApexSaveChatBotLead.class);
	}

    
}