force-app/main/default/objects/Account/fields/IMS_PIN__c.field-meta.xml
<CustomField>
    <fullName>IMS_PIN__c</fullName>
    <label>IMS PIN</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Mode</label>
    <referenceTo>Lead_Mode__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source.</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Mode_PickList__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Justdial</fullName>
            </value>
            <value>
                <fullName>Sulekha</fullName>
            </value>
            <value>
                <fullName>Urbanpro</fullName>
            </value>
            <value>
                <fullName>Shiksha</fullName>
            </value>
            <value>
                <fullName>Studysid</fullName>
            </value>
            <value>
                <fullName>Google Adwords</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>College Seminars</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Tollfree</fullName>
            </value>
            <value>
                <fullName>Email Enquiry</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Education Fairs</fullName>
            </value>
            <value>
                <fullName>IMS Events</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
                <isActive>false</isActive>
                <label>Classroom</label>
            </value>
            <value>
                <fullName>Comprehensive</fullName>
                <isActive>false</isActive>
                <label>Comprehensive</label>
            </value>
            <value>
                <fullName>Correspondence</fullName>
                <isActive>false</isActive>
                <label>Correspondence</label>
            </value>
            <value>
                <fullName>Test Series Online</fullName>
                <isActive>false</isActive>
                <label>Test Series Online</label>
            </value>
            <value>
                <fullName>Website queries</fullName>
                <isActive>false</isActive>
                <label>Website queries</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Counselling</fullName>
            </value>
            <value>
                <fullName>Partially Enrolled</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
                <isActive>false</isActive>
                <label>Converted</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Enrolled</fullName>
                <isActive>false</isActive>
                <label>Not Enrolled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/LIMA_Check__c.field-meta.xml
<CustomField>
    <fullName>LIMA_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LIMA Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mailing City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Student  Accounts (Mailing City)</relationshipLabel>
    <relationshipName>Student_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Permanent_City__c.field-meta.xml
<CustomField>
    <fullName>Permanent_City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permanent City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Student  Accounts</relationshipLabel>
    <relationshipName>Student_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preference__c.field-meta.xml
<CustomField>
    <fullName>Preference__c</fullName>
    <label>Preference</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Present_In_LIMA__c.field-meta.xml
<CustomField>
    <fullName>Present_In_LIMA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Present In LIMA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product_delivery_mode__c.field-meta.xml
<CustomField>
    <fullName>Product_delivery_mode__c</fullName>
    <label>Product delivery mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Classroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Referral_Centre__c.field-meta.xml
<CustomField>
    <fullName>Referral_Centre__c</fullName>
    <label>Referral Centre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <label>Referred By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Students</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Student_Referral_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Referral_Name__c</fullName>
    <label>Student Referral Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/City_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Code__c</fullName>
    <label>City Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <label>Web to Lead Mode</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Mode__c/Lead_Mode__c.object-meta.xml
<CustomObject>
    <label>Lead Mode</label>
    <nameField>
        <label>Lead Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Source__c/Lead_Source__c.object-meta.xml
<CustomObject>
    <label>Lead Source</label>
    <nameField>
        <label>Lead Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Source__c/fields/Lead_Mode__c.field-meta.xml
<CustomField>
    <fullName>Lead_Mode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Mode</label>
    <referenceTo>Lead_Mode__c</referenceTo>
    <relationshipLabel>Lead Sources</relationshipLabel>
    <relationshipName>Lead_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RESTGetLIMALead.cls
public class RESTGetLIMALead {
    public Boolean b = false;
    public Boolean c = false;
    public PageReference RESTGetLIMALeadAction(){
        String stid = ApexPages.currentPage().getParameters().get('id');
        System.debug('id-->'+stid);
        List<Account> acc = [SELECT Id, LastName, IMS_PIN__c, PersonEmail, PersonMobilePhone FROM Account WHERE Id=:stid];
        System.debug('Account record-->'+acc[0]);
        If(acc[0].PersonEmail!=Null&&acc[0].PersonEmail!=''){
            c = getCallWithEmail(acc[0].PersonEmail,acc[0]);
            if(c){
                pagereference pg= new pagereference('/'+stid);
                pg.setRedirect(true);
                return pg;
            }
        }If(acc[0].PersonMobilePhone!=''&&acc[0].PersonMobilePhone!=Null&&!c){
            c = getCallWithMobile(acc[0].PersonMobilePhone,acc[0]);
            if(c){
                pagereference pg= new pagereference('/'+stid);
                pg.setRedirect(true);
                return pg;
            }else{
                pagereference pg= new pagereference('/'+stid);
                pg.setRedirect(true);
                return pg;
            }
        }
        
        pagereference pg= new pagereference('/'+stid);
        
        pg.setRedirect(true);
        return pg;
        
    }
    
    public Boolean getCallWithEmail(String email,Account acc){
        
        List<Account> upAcc = new List<Account>();        
        //email = 'dipesh.agre@enlitenit.com';
        String js = '{\"txtemail\":\"'+email+'\"}';
        String s = '';
        Http h = new Http();		
        HttpRequest req = new HttpRequest();
        
        req.setMethod('POST');
        req.setBody(js);
        req.setHeader('Content-Type', 'text/plain');
        req.setEndpoint('https://lima.imsindia.com/SF_API/default.aspx/?action=getlead');//sandbox url
        System.debug('The request is get Lead from Email---'+req.getBody());
        HttpResponse res = h.send(req);
        System.debug('Response came from request Email->'+res.getBody());
        JSON2ApexLIMALead ll = JSON2ApexLIMALead.parse(res.getBody());
        
        System.debug('ll.mtype--'+ll.mtype);
        IF(ll.mtype!='success'){
            b = false;
            acc.LIMA_Check__c = True;
        }else{
            b = true;
            String mCityCode  = ll.StudentAccount.MailingCityCode;
            String bCityCode  = ll.StudentAccount.CityCode;  
            List<City__c> mCityList = [SELECT ID, Name, City_Code__c FROM City__c WHERE City_Code__c=:mCityCode];
            List<City__c> bCityList = [SELECT ID, Name, City_Code__c FROM City__c WHERE City_Code__c=:bCityCode];
            
            If(mCityList.size()>0){
                acc.Mailing_City__c = mCityList[0].City_Code__c;
            }
            If(bCityList.size()>0){
                acc.Permanent_City__c = bCityList[0].City_Code__c;
            }
            
            System.debug('mtypemtypemtype'+ll.StudentAccount);
            acc.IMS_PIN__c = ll.StudentAccount.IMSPIN;
            acc.FirstName = ll.StudentAccount.FirstName;
            acc.MiddleName = ll.StudentAccount.MiddleName;
            IF(ll.StudentAccount.LastName!=''){
                acc.LastName = ll.StudentAccount.LastName;
            }
            else{
                IF(ll.StudentAccount.FirstName!=''){
                    acc.LastName = ll.StudentAccount.FirstName;
                }
            }
            
            acc.PersonMobilePhone = ll.StudentAccount.Mobile1;
            
            
            acc.Description = ll.StudentAccount.Description;
            acc.Lead_Stage__c = ll.StudentAccount.LeadStage;
            acc.Preference__c = ll.StudentAccount.Preference;
            acc.Referred_By__c = ll.StudentAccount.ReferredBy;
            acc.Employee_Referral_Name__c = ll.StudentAccount.employeeReferralName;
            acc.Student_Referral_Name__c = ll.StudentAccount.StudentReferralName;
            acc.Referral_Centre__c = ll.StudentAccount.ReferralCentre;
            acc.Lead_Mode__c = ll.StudentAccount.LeadMode;
            //acc.Lead_Source__c = ll.StudentAccount.LeadSource;
            acc.Product_delivery_mode__c = ll.StudentAccount.ProductDeliveryMode;
            acc.PersonMailingStreet = ll.StudentAccount.MailingStreet;
            acc.PersonMailingCity = ll.StudentAccount.MailingCity;
            
            acc.PersonMailingPostalCode = ll.StudentAccount.MailingPinCode;
            acc.PersonMailingState = ll.StudentAccount.MailingState;
            acc.PersonMailingCountry = ll.StudentAccount.MailingCountry;
            acc.BillingStreet = ll.StudentAccount.Street;
            acc.BillingCity = ll.StudentAccount.City;
            
            acc.BillingPostalCode = ll.StudentAccount.PinCode;
            acc.BillingState = ll.StudentAccount.State;
            acc.BillingCountry = ll.StudentAccount.Country;
            
            
            
            acc.LIMA_Check__c = True;
            acc.Present_In_LIMA__c = True;
            upAcc.add(acc);
            update upAcc;
        }
        System.debug('bbbbbbbb'+b);
        return b;
        
        
    } 
    public Boolean getCallWithMobile(String mobile,Account acc){
        
        String js = '{"txtmobile\":\"'+mobile+'\"}';
        String s = '';
        Http h = new Http();		
        HttpRequest req = new HttpRequest();
        
        req.setMethod('POST');
        req.setBody(js);
        req.setTimeout(120000);
        req.setHeader('Content-Type','text/plain');
        //req.setHeader('token', s);
        req.setEndpoint('https://lima.imsindia.com/SF_API/default.aspx/?action=getlead');//sandbox url
        
        System.debug('The request is get Lead from Mobile---'+req);
        HttpResponse res = h.send(req);
        System.debug('Response came from request Email->'+res.getBody());
        JSON2ApexLIMALead ll = JSON2ApexLIMALead.parse(res.getBody());
        System.debug('mtypemtypemtype'+ll.StudentAccount);
        System.debug('ll.mtype--'+ll.mtype);
        IF(ll.mtype!='success'){
            b = false;
        }else{
            b = true;
            String mCityCode  = ll.StudentAccount.MailingCityCode;
            String bCityCode  = ll.StudentAccount.CityCode;  
            List<City__c> mCityList = [SELECT ID, Name, City_Code__c FROM City__c WHERE City_Code__c=:mCityCode];
            List<City__c> bCityList = [SELECT ID, Name, City_Code__c FROM City__c WHERE City_Code__c=:bCityCode];
            
            If(mCityList.size()>0){
                acc.Mailing_City__c = mCityList[0].Id;
            }
            If(bCityList.size()>0){
                acc.Permanent_City__c = bCityList[0].Id;
            }
            
            System.debug('mtypemtypemtype'+ll.StudentAccount);
            acc.IMS_PIN__c = ll.StudentAccount.IMSPIN;
            acc.FirstName = ll.StudentAccount.FirstName;
            acc.MiddleName = ll.StudentAccount.MiddleName;
            System.debug('ll.StudentAccount.LastName-->'+ll.StudentAccount.LastName);
            System.debug('ll.StudentAccount.First-->'+ll.StudentAccount.FirstName);
            IF(ll.StudentAccount.LastName!=''){
                acc.LastName = ll.StudentAccount.LastName;
            }
            else{
                IF(ll.StudentAccount.FirstName!=''){
                    acc.LastName = ll.StudentAccount.FirstName;
                }
            }
            acc.PersonMobilePhone = ll.StudentAccount.Mobile1;
            
            
            acc.Description = ll.StudentAccount.Description;
            acc.Lead_Stage__c = ll.StudentAccount.LeadStage;
            acc.Preference__c = ll.StudentAccount.Preference;
            acc.Referred_By__c = ll.StudentAccount.ReferredBy;
            acc.Employee_Referral_Name__c = ll.StudentAccount.employeeReferralName;
            acc.Student_Referral_Name__c = ll.StudentAccount.StudentReferralName;
            acc.Referral_Centre__c = ll.StudentAccount.ReferralCentre;
            //acc.Lead_Mode__c = ll.StudentAccount.LeadMode;
            //acc.Lead_Source__c = ll.StudentAccount.LeadSource;
            acc.Product_delivery_mode__c = ll.StudentAccount.ProductDeliveryMode;
            acc.PersonMailingStreet = ll.StudentAccount.MailingStreet;
            acc.PersonMailingCity = ll.StudentAccount.MailingCity;
            
            acc.PersonMailingPostalCode = ll.StudentAccount.MailingPinCode;
            acc.PersonMailingState = ll.StudentAccount.MailingState;
            acc.PersonMailingCountry = ll.StudentAccount.MailingCountry;
            acc.BillingStreet = ll.StudentAccount.Street;
            acc.BillingCity = ll.StudentAccount.City;
            
            acc.BillingPostalCode = ll.StudentAccount.PinCode;
            acc.BillingState = ll.StudentAccount.State;
            acc.BillingCountry = ll.StudentAccount.Country;
            
            
            
            acc.LIMA_Check__c = True;
            acc.Present_In_LIMA__c = True;
            //upAcc.add(acc);
            update acc;
        }
        System.debug('bbbbbbbb'+b);
        return b;
        
        
    }
    
    //
    // Generated by JSON2Apex http://json2apex.herokuapp.com/
    //
    
    public class JSON2ApexLIMALead {
        
        public StudentAccount StudentAccount;
        public String mtype;
        public String message;
    }
    
    public class StudentAccount {
        public String IMSPIN;
        public String FirstName;
        public String MiddleName;
        public String LastName;
        public String Email;
        public String Mobile1;
        public String Mobile2;
        public String Order;
        public String Description;
        public String LeadStage;
        public String Preference;
        public String ReferredBy;
        public String EmployeeReferralName;
        public String StudentReferralName;
        public String ReferralCentre;
        
        public String LeadMode;
        public String LeadSource;
        
        public String Priority;
        public String ProductDeliveryMode;
        public String Productwise;
        public String MailingStreet;
        public String MailingCity;
        public String MailingCityCode;
        public String MailingPinCode;
        public String MailingState;
        public String MailingCountry;
        public String Street;
        public String City;
        public String CityCode;
        public String PinCode;
        public String State;
        public String Country;
        //public List<MailingCity> MailingCity;
        //public List<MailingCity> PermanentCity;
    }
    
    public class MailingCity {
    }
    
    
    public static JSON2ApexLIMALead parse(String json) {
        return (JSON2ApexLIMALead) System.JSON.deserialize(json, JSON2ApexLIMALead.class);
    }
    
    
}