force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Program_Category__c.field-meta.xml
<CustomField>
    <fullName>Program_Category__c</fullName>
    <label>Program Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BGE</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>UG</fullName>
            </value>
            <value>
                <fullName>SA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_University__c/Program_University__c.object-meta.xml
<CustomObject>
    <label>Program / University</label>
    <nameField>
        <displayFormat>PU{0000}</displayFormat>
        <label>Program / University No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program / University</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_University__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program / University</relationshipLabel>
    <relationshipName>Program_University</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_University__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>University</label>
    <referenceTo>University_Board__c</referenceTo>
    <relationshipLabel>Program / University</relationshipLabel>
    <relationshipName>Program_University</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AddPrograms.cls
public class AddPrograms {
    
    public List < Program_University__c  > selist {get;set;}
    public Id opid {get;set;}
    Static Id sId;
    public List<wrTra> wrlist{get; set;}          
    public String wrlist1 {get; set;}
    set<String> acctben = new set<String>();
    
    public AddPrograms() {
        
        opid = ApexPages.currentPage().getParameters().get('id');
        sId = opid;
        System.debug('SID'+sId);
        wrlist = new List<wrTra>(); 
        
        for(Program_University__c  ab: [SELECT Id, Name, Program__c ,University__c FROM Program_University__c Where University__c =:opid ]){
            
            acctben.add(ab.Program__c);
            system.debug('acctben------'+acctben);
        }
        
        for(Program__c tc:[  SELECT  Id, Name, Program_Code__c, Program_Category__c, Status__c 
                             FROM Program__c where Status__c='Active' and Id NOT IN :acctben order by name]){
                                 
                                 System.debug('====> data: ' + JSON.serialize(tc));    
                                 wrlist.add(new wrTra(tc));
                             }
        wrlist1 = JSON.serialize(wrlist);
    }
    
    @RemoteAction
    public static void save(String json, String id) {
        
        List<wrTra> wrlist = parsewTra(json);        
        List<Program_University__c > selist=new List<Program_University__c >();
        
        for(wrTra wt:wrlist){ 
            if(wt.chk){
                
                Program_University__c  oppt = new Program_University__c ();
                oppt.University__c= id;
                oppt.Program__c=wt.tra.id;                 
                selist.add(oppt);
                system.debug('selist------------'+selist);
            }           
        }
        insert selist;
        
        PageReference pageRef = new PageReference('/' + id);
        pageRef.setRedirect(true);
    }
    
    public static List<wrTra> parsewTra(String json) {
        return (List<wrTra>) System.JSON.deserialize(json, List<wrTra>.class);
    }
    
    public PageReference cancel() {
        
        PageReference pageRef = new PageReference('/' + opid);
        pageRef.setRedirect(true);
        return pageRef;      
    }
    
    public class wrTra{
        
        public Program__c   tra {get;set;}
        public Boolean chk{get;set;}
        
        public wrTra(Program__c   doc){
            this.tra=doc;
            this.chk=false;
        }
    }   
    
}