force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_University__c/Program_University__c.object-meta.xml
<CustomObject>
    <label>Program / University</label>
    <nameField>
        <displayFormat>PU{0000}</displayFormat>
        <label>Program / University No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program / University</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_University__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program / University</relationshipLabel>
    <relationshipName>Program_University</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_University__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>University</label>
    <referenceTo>University_Board__c</referenceTo>
    <relationshipLabel>Program / University</relationshipLabel>
    <relationshipName>Program_University</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/University_Board__c/University_Board__c.object-meta.xml
<CustomObject>
    <label>University/Board</label>
    <nameField>
        <label>University/Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>University/Board</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/University_Board__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SSC (Xth)</fullName>
            </value>
            <value>
                <fullName>HSC (XIIth)</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Post-graduation</fullName>
            </value>
            <value>
                <fullName>Professional Certification</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddUniversity.cls
public class AddUniversity {
    
    public List < Program_University__c  > selist {get;set;}
    public Id opid {get;set;}
    Static Id sId;
    public List<wrTra> wrlist{get; set;}          
    public String wrlist1 {get; set;}
    set<String> acctben = new set<String>();
    
    public AddUniversity() {
        
        opid = ApexPages.currentPage().getParameters().get('id');
        sId = opid;
        System.debug('SID'+sId);
        wrlist = new List<wrTra>(); 
        
        for(Program_University__c  ab: [SELECT Id, Name, Program__c ,University__c FROM Program_University__c Where  Program__c =:opid ]){
            
            acctben.add(ab.University__c);
            system.debug('acctben------'+acctben);
        }
        
        for(University_Board__c  tc:[  SELECT  Id, Name, Type__c  FROM University_Board__c  where Id NOT IN :acctben order by name]){
            
            System.debug('====> data: ' + JSON.serialize(tc));    
            wrlist.add(new wrTra(tc));
        }
        wrlist1 = JSON.serialize(wrlist);
    }
    
    @RemoteAction
    public static void save(String json, String id) {
        
        List<wrTra> wrlist = parsewTra(json);        
        List<Program_University__c > selist=new List<Program_University__c >();
        
        for(wrTra wt:wrlist){ 
            if(wt.chk){
                
                Program_University__c  oppt = new Program_University__c ();
                oppt.Program__c= id;
                oppt.University__c=wt.tra.id;                
                selist.add(oppt);
                system.debug('selist------------'+selist);
            }           
        }
        insert selist;
        
        PageReference pageRef = new PageReference('/' + id);
        pageRef.setRedirect(true);
    }
    
    public static List<wrTra> parsewTra(String json) {
        return (List<wrTra>) System.JSON.deserialize(json, List<wrTra>.class);
    }
    
    public PageReference cancel() {
        
        PageReference pageRef = new PageReference('/' + opid);
        pageRef.setRedirect(true);
        return pageRef;      
    }
    
    public class wrTra{
        
        public University_Board__c  tra {get;set;}
        public Boolean chk{get;set;}
        
        public wrTra(University_Board__c  doc){
            this.tra=doc;
            this.chk=false;
        }
    }   
    
}