force-app/main/default/objects/Centre_City__c/Centre_City__c.object-meta.xml
<CustomObject>
    <label>Centre City</label>
    <nameField>
        <label>Centre City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre City</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Centre_City__c/fields/City_Code__c.field-meta.xml
<CustomField>
    <fullName>City_Code__c</fullName>
    <label>City Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SampleTestClass.cls
public class SampleTestClass {//have written for Centre class

     
    public void getRecords(){
        
        List<String> cCode = new List<String>();
        Integer totalCount =  [SELECT count() FROM Centre_City__c];
        System.debug('Total count --->'+totalCount);
        
        For(Integer i = 0; i<=totalCount;){
            Integer max = 50;
            cCode = getCode(max,i);
            System.debug('After i'+i+cCode);
            RESTGetCentreBatch rgcb = new RESTGetCentreBatch(cCode);
            Database.executeBatch(rgcb, 50);//(rgcb,cCode);
            
            i = i+max;
            
        }
        
    }
    
    public List<String> getCode(Integer max, Integer off){
        String cityCode = '';
        List<Centre_City__c> cList = [SELECT ID, Name, City_Code__c FROM Centre_City__c ORDER BY ID LIMIT:Max Offset: off];
        List<String> codeList = new List<String>();
            
        For(Centre_City__c c:cList){
            
                codeList.add(c.City_Code__c);
            
        }
        
        //System.debug('I am printing the final list of CityCode'+cityCode);
        return codeList;
    }
}