force-app/main/default/objects/Academic_Profile__c/Academic_Profile__c.object-meta.xml
<CustomObject>
    <label>Academic Profile</label>
    <nameField>
        <displayFormat>AP{0000}</displayFormat>
        <label>Academic Profile No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Academic Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Academic_Profile__c/fields/Profile_Discovery__c.field-meta.xml
<CustomField>
    <fullName>Profile_Discovery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile Discovery</label>
    <referenceTo>Profile_Discovery__c</referenceTo>
    <relationshipLabel>Academic Profile</relationshipLabel>
    <relationshipName>Academic_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Academic_Profile__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Academic Profile</relationshipLabel>
    <relationshipName>Academic_Profile</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Achievement  ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Achievement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/Profile_Discovery__c.field-meta.xml
<CustomField>
    <fullName>Profile_Discovery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile Discovery</label>
    <referenceTo>Profile_Discovery__c</referenceTo>
    <relationshipLabel>Achievement</relationshipLabel>
    <relationshipName>Achievement</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aspiration__c/Aspiration__c.object-meta.xml
<CustomObject>
    <label>Aspiration</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>Aspiration No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aspiration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aspiration__c/fields/Profile_Discovery__c.field-meta.xml
<CustomField>
    <fullName>Profile_Discovery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile Discovery</label>
    <referenceTo>Profile_Discovery__c</referenceTo>
    <relationshipLabel>Aspiration</relationshipLabel>
    <relationshipName>Aspiration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Centre__c/Centre__c.object-meta.xml
<CustomObject>
    <label>Centre</label>
    <nameField>
        <label>Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centre</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling__c/Counselling__c.object-meta.xml
<CustomObject>
    <label>Counselling</label>
    <nameField>
        <label>Counselling ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counselling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Counselling</relationshipLabel>
    <relationshipName>Counselling</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/Counselling_Centre__c.object-meta.xml
<CustomObject>
    <label>Centre*</label>
    <nameField>
        <displayFormat>CN{0000}</displayFormat>
        <label>Centre	No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Centre*</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling_Centre__c/fields/Centre__c.field-meta.xml
<CustomField>
    <fullName>Centre__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Centre</label>
    <referenceTo>Centre__c</referenceTo>
    <relationshipName>Centre</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Centre__c/fields/Counselling__c.field-meta.xml
<CustomField>
    <fullName>Counselling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counselling</label>
    <referenceTo>Counselling__c</referenceTo>
    <relationshipLabel>Centre*</relationshipLabel>
    <relationshipName>Centre</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Program__c/Counselling_Program__c.object-meta.xml
<CustomObject>
    <label>Program*</label>
    <nameField>
        <displayFormat>PN{0000}</displayFormat>
        <label>Program No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program*</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Counselling_Program__c/fields/Counselling__c.field-meta.xml
<CustomField>
    <fullName>Counselling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counselling</label>
    <referenceTo>Counselling__c</referenceTo>
    <relationshipName>Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Counselling_Program__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipName>Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institute__c/Institute__c.object-meta.xml
<CustomObject>
    <label>Institute</label>
    <nameField>
        <displayFormat>I{0000}</displayFormat>
        <label>Institute No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institute</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_and_Hobbies__c/Interest_and_Hobbies__c.object-meta.xml
<CustomObject>
    <label>Interest and Hobbies</label>
    <nameField>
        <displayFormat>IH{0000}</displayFormat>
        <label>Interest and Hobbies No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest and Hobbies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_and_Hobbies__c/fields/Interest_And_Hobbies__c.field-meta.xml
<CustomField>
    <fullName>Interest_And_Hobbies__c</fullName>
    <label>Interest And Hobbies</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Interest_and_Hobbies__c/fields/Profile_Discovery__c.field-meta.xml
<CustomField>
    <fullName>Profile_Discovery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile Discovery</label>
    <referenceTo>Profile_Discovery__c</referenceTo>
    <relationshipLabel>Interest and Hobbies</relationshipLabel>
    <relationshipName>Interest_and_Hobbies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile_Discovery__c/Profile_Discovery__c.object-meta.xml
<CustomObject>
    <label>Profile Discovery</label>
    <nameField>
        <displayFormat>PD{0000}</displayFormat>
        <label>Profile Discovery ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profile Discovery</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile_Discovery__c/fields/Counselling__c.field-meta.xml
<CustomField>
    <fullName>Counselling__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Counselling</label>
    <referenceTo>Counselling__c</referenceTo>
    <relationshipLabel>Profile Discovery</relationshipLabel>
    <relationshipName>Profile_Discovery</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Target_Institutes__c/Target_Institutes__c.object-meta.xml
<CustomObject>
    <label>Target Institutes</label>
    <nameField>
        <displayFormat>TI{0000}</displayFormat>
        <label>Target Institutes No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Target Institutes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Institutes__c/fields/Aspiration__c.field-meta.xml
<CustomField>
    <fullName>Aspiration__c</fullName>
    <label>Aspiration</label>
    <referenceTo>Aspiration__c</referenceTo>
    <relationshipLabel>Target Institutes</relationshipLabel>
    <relationshipName>Target_Institutes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Target_Institutes__c/fields/Institute__c.field-meta.xml
<CustomField>
    <fullName>Institute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Institute</label>
    <referenceTo>University_Board__c</referenceTo>
    <relationshipLabel>Target Institutes</relationshipLabel>
    <relationshipName>Target_Institutes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/University_Board__c/University_Board__c.object-meta.xml
<CustomObject>
    <label>University/Board</label>
    <nameField>
        <label>University/Board Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>University/Board</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentCounsellingPlatformManager.cls
public without sharing class StudentCounsellingPlatformManager {
    public StudentCounsellingPlatformManager() {

    }

    @AuraEnabled(cacheable=false)
    public static returnCounsellingApex createCounselling(String accountRecordId,String centerRecordId,String productRecordId){
        returnCounsellingApex rcApex = new returnCounsellingApex();
        try {

            List<Counselling__c> listCounselling = new List<Counselling__c>();
            listCounselling = [ SELECT Id,Name,(SELECT Id,Name FROM Centre__r LIMIT 1 )
            ,(SELECT Id,Name FROM Profile_Discovery__r LIMIT 1 )
            ,(SELECT Id,Name FROM Program__r LIMIT 1 ) FROM Counselling__c WHERE Student__c =: accountRecordId LIMIT 1 ];
            if(listCounselling.size() > 0){
                rcApex.Counselling_id = listCounselling[0].Id;
                rcApex.Counselling_Centre_id = listCounselling[0].Centre__r[0].Id;
                rcApex.Profile_Discovery_id = listCounselling[0].Profile_Discovery__r[0].Id;
                rcApex.Counselling_Program_id = listCounselling[0].Program__r[0].Id;
                rcApex.status = true;
                rcApex.message = 'success';
            }else{

                Counselling__c Counselling = new Counselling__c();
                Counselling.Student__c = accountRecordId;
                insert Counselling;
                
                rcApex.Counselling_id = Counselling.id;
                
                Counselling_Centre__c Counselling_Centre = new Counselling_Centre__c(); 
                Counselling_Centre.Centre__c = centerRecordId;
                Counselling_Centre.Counselling__c = Counselling.id;
    
                insert Counselling_Centre;
    
                rcApex.Counselling_Centre_id = Counselling_Centre.id;
    
                Counselling_Program__c Counselling_Program = new Counselling_Program__c(); 
                Counselling_Program.Counselling__c = Counselling.id;
                Counselling_Program.Product__c = productRecordId;
                insert Counselling_Program;
                
                rcApex.Counselling_Program_id = Counselling_Program.id;
                
                Profile_Discovery__c Profile_Discovery = new Profile_Discovery__c(); 
                Profile_Discovery.Counselling__c = Counselling.id;
                insert Profile_Discovery;
                
                rcApex.Profile_Discovery_id = Profile_Discovery.id;
                rcApex.status = true;
                rcApex.message = 'success';
            }

            return rcApex;
        } catch (Exception e) {
            rcApex.status = false;
            rcApex.message =  String.valueOf(e);
            // throw new AuraHandledException(e.getMessage());
            return rcApex;
        }
    }

    @AuraEnabled(cacheable=false)
    public static string getAcademicProfileId(String recordId){
        try {
            Academic_Profile__c apc = [SELECT Id,Name FROM Academic_Profile__c WHERE Profile_Discovery__c =: recordId LIMIT 1];
            return apc.Id;
        } catch (Exception e) {
            // throw new AuraHandledException(e.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=false)
    public static string getaspirationId(String recordId){
        try {
            Aspiration__c apc = [SELECT Id,Name FROM Aspiration__c WHERE Profile_Discovery__c =: recordId LIMIT 1];
            return apc.Id;
        } catch (Exception e) {
            // throw new AuraHandledException(e.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<Interest_and_Hobbies__c> getInterestAndHpobbies(String profileDiscoveryRecordId){
        try {
            List<Interest_and_Hobbies__c> IAH = [SELECT Id,Name,Interest_And_Hobbies__c  FROM Interest_and_Hobbies__c WHERE Profile_Discovery__c =: profileDiscoveryRecordId   ];
            return IAH;
        } catch (Exception e) {
            // throw new AuraHandledException(e.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<Achievement__c> getAchivements(String profileDiscoveryRecordId){
        try {
            List<Achievement__c> IAH = [SELECT Id,Name,Achievement__c FROM Achievement__c WHERE Profile_Discovery__c =: profileDiscoveryRecordId   ];
            return IAH;
        } catch (Exception e) {
            // throw new AuraHandledException(e.getMessage());
            return null;
        }
    }

    @AuraEnabled(cacheable=false)
    public static List<Target_Institutes__c> getTargetAndInstitue(String aspirationRecordId){
        try {
            List<Target_Institutes__c> IAH = [SELECT Id,Name,Aspiration__c,Institute__c,Institute__r.Name,Institute__r.Id FROM Target_Institutes__c WHERE Aspiration__c =: aspirationRecordId   ];
            return IAH;
        } catch (Exception e) {
            // throw new AuraHandledException(e.getMessage());
            return null;
        }
    }

    public class returnCounsellingApex{
        @AuraEnabled
        public boolean status;
        @AuraEnabled
        public String message;
        @AuraEnabled
        public string Counselling_Program_id;
        @AuraEnabled
        public string Profile_Discovery_id;
        @AuraEnabled
        public string Counselling_Centre_id;
        @AuraEnabled
        public string Counselling_id;
    }
}